export const ADD_EXPENSE = 'ADD_EXPENSE';
export const ADD_EXPENSE_SUCCESS= 'ADD_EXPENSE_SUCCESS';
export const ADD_EXPENSE_FAILED= 'ADD_EXPENSE_FAILED';


export const DELETE_EXPENSE = 'DELETE_EXPENSE';

export const EDIT_EXPENSE = 'EDIT_EXPENSE';

 