export const ADD_EXPENSE = 'ADD_EXPENSE';

export const ADD_EXPENSE_FAILED= 'ADD_EXPENSE_FAILED';


export const DELETE_EXPENSE = 'DELETE_EXPENSE';

export const EDIT_EXPENSE = 'EDIT_EXPENSE';


export const LOGIN = 'LOGIN';
export const SIGNUP = 'SIGNUP';
export const AUTH_START = 'AUTH_START';
export const AUTH_SUCCESS = 'AUTH_SUCCESS';
export const SIGNUP_FAILED = 'SIGNUP_FAILED';
export const AUTH_FAILED = 'AUTH_FAILED';
export const LOGIN_FAILED = 'LOGIN_FAILED';
export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const AUTH_LOGOUT = 'AUTH_LOGOUT';


export const ADD_EXPENSE_START = 'ADD_EXPENSE_START';
export const ADD_EXPENSE_SUCCESS = 'ADD_EXPENSE_SUCCESS';

export const FETCH_EXPENSE_START = 'FETCH_EXPENSE_START';
export const FETCH_EXPENSE_SUCCESS = 'FETCH_EXPENSE_SUCCESS';
export const FETCH_EXPENSE_FAILED = 'FETCH_EXPENSE_FAILED';

export const DELETE_EXPENSE_SUCCESS = 'DELETE_EXPENSE_SUCCESS';
export const DELETE_EXPENSE_FAILED = 'DELETE_EXPENSE_FAILED';





 